import{a as E,S as w,i as c}from"./assets/vendor-B7yatFIi.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();async function f(r,a=1,e=15){const o="https://pixabay.com/api/",t="51376542-95e34f1d639dab3c27f4a47b0",s=new URLSearchParams({q:r,key:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:e,page:a});try{return(await E.get(`${o}?${s}`)).data}catch(l){throw l}}const b=new w(".gallery a");function g(r){const a=r.map(e=>`<li><a class="img-link" href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"><ul class="img-meta">
      <li class="meta-list-item"><span class="meta-item-title">Likes</span> ${e.likes===""?"n/d":e.likes}</li>
      <li class="meta-list-item"><span class="meta-item-title">Views</span> ${e.views===""?"n/d":e.views}</li>
      <li class="meta-list-item"><span class="meta-item-title">Comments</span> ${e.comments===""?"n/d":e.comments}</li>
      <li class="meta-list-item"><span class="meta-item-title">Downloads</span> ${e.downloads===""?"n/d":e.downloads}</li>
      </ul>
      </a>
      </li>`).join("");i.galleryEl.insertAdjacentHTML("beforeend",a),b.refresh()}function M(){i.galleryEl.innerHTML=""}function p(){i.loaderEl.classList.remove("is-hidden")}function h(){i.loaderEl.classList.add("is-hidden")}function y(){i.loadMoreBtn.classList.remove("is-hidden")}function d(){i.loadMoreBtn.classList.add("is-hidden")}const i={formEl:document.querySelector(".form"),galleryEl:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn"),loaderEl:document.querySelector(".loader")},m=15;let L="",n=1,u=1;i.formEl.addEventListener("submit",v);i.loadMoreBtn.addEventListener("click",S);i.galleryEl.addEventListener("click",P);function P(r){r.target.nodeName==="IMG"&&r.preventDefault()}async function v(r){r.preventDefault(),M();let a=null;const e=r.target.elements["search-text"].value.trim();if(!e)return c.error({message:"Empty request. Try again!",position:"topRight"});L=e,d(),p(),n=1;try{a=await f(e,n,m);const o=a.hits;if(o.length===0)return c.error({message:"Sorry there are no images matching your search query. Please try again!",position:"topRight"});g(o)}catch(o){c.error({message:o.message,position:"topRight"})}finally{h(),u=Math.ceil(a.totalHits/m),n!==u&&y()}r.target.reset()}async function S(){d(),p(),n+=1;try{const a=(await f(L,n)).hits;g(a);const o=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}catch(r){c.error({message:r.message,position:"topRight"})}finally{h(),n===u?(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):y()}}
//# sourceMappingURL=index.js.map
