import{a as E,S as w,i as n}from"./assets/vendor-B7yatFIi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();async function m(a,r=1,e=15){const o="https://pixabay.com/api/",t="51376542-95e34f1d639dab3c27f4a47b0",s=new URLSearchParams({q:a,key:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:e,page:r});try{return(await E.get(`${o}?${s}`)).data}catch(l){throw l}}const b=new w(".gallery a");function f(a){const r=a.map(e=>`<li><a class="img-link" href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"><ul class="img-meta">
      <li class="meta-list-item"><span class="meta-item-title">Likes</span> ${e.likes===""?"n/d":e.likes}</li>
      <li class="meta-list-item"><span class="meta-item-title">Views</span> ${e.views===""?"n/d":e.views}</li>
      <li class="meta-list-item"><span class="meta-item-title">Comments</span> ${e.comments===""?"n/d":e.comments}</li>
      <li class="meta-list-item"><span class="meta-item-title">Downloads</span> ${e.downloads===""?"n/d":e.downloads}</li>
      </ul>
      </a>
      </li>`).join("");i.galleryEl.insertAdjacentHTML("beforeend",r),b.refresh()}function M(){i.galleryEl.innerHTML=""}function g(){i.loaderEl.classList.remove("is-hidden")}function p(){i.loaderEl.classList.add("is-hidden")}function h(){i.loadMoreBtn.classList.remove("is-hidden")}function u(){i.loadMoreBtn.classList.add("is-hidden")}const i={formEl:document.querySelector(".form"),galleryEl:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn"),loaderEl:document.querySelector(".loader")},d=15;let y="",c=1,L=1;i.formEl.addEventListener("submit",v);i.loadMoreBtn.addEventListener("click",S);i.galleryEl.addEventListener("click",P);function P(a){a.target.nodeName==="IMG"&&a.preventDefault()}async function v(a){a.preventDefault(),M();let r=null;const e=a.target.elements["search-text"].value.trim();if(!e)return n.error({message:"Empty request. Try again!",position:"topRight"});y=e,u(),g(),c=1;try{r=await m(e,c,d);const o=r.hits;if(o.length===0)return n.error({message:"Sorry there are no images matching your search query. Please try again!",position:"topRight"});f(o)}catch(o){n.error({message:o.message,position:"topRight"})}finally{p(),L=Math.ceil(r.totalHits/d),r.totalHits>d&&h()}a.target.reset()}async function S(){u(),g(),c+=1;try{const r=(await m(y,c)).hits;f(r);const o=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}catch(a){n.error({message:a.message,position:"topRight"})}finally{p(),c>=L?(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):h()}}
//# sourceMappingURL=index.js.map
