import{a as L,S as E,i as l}from"./assets/vendor-B7yatFIi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();async function u(a,r=1){const e="https://pixabay.com/api/",i="51376542-95e34f1d639dab3c27f4a47b0",t=new URLSearchParams({q:a,key:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:o.per_page,page:r});try{return(await L.get(`${e}?${t}`)).data}catch(s){throw s}}const w=new E(".gallery a");function m(a){const r=a.map(e=>`<li><a class="img-link" href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"><ul class="img-meta">
      <li class="meta-list-item"><span class="meta-item-title">Likes</span> ${e.likes===""?"n/d":e.likes}</li>
      <li class="meta-list-item"><span class="meta-item-title">Views</span> ${e.views===""?"n/d":e.views}</li>
      <li class="meta-list-item"><span class="meta-item-title">Comments</span> ${e.comments===""?"n/d":e.comments}</li>
      <li class="meta-list-item"><span class="meta-item-title">Downloads</span> ${e.downloads===""?"n/d":e.downloads}</li>
      </ul>
      </a>
      </li>`).join("");o.galleryEl.insertAdjacentHTML("beforeend",r),w.refresh()}function b(){o.galleryEl.innerHTML=""}function p(){o.loaderEl.classList.remove("is-hidden")}function g(){o.loaderEl.classList.add("is-hidden")}function f(){o.loadMoreBtn.classList.remove("is-hidden")}function d(){o.loadMoreBtn.classList.add("is-hidden")}const o={formEl:document.querySelector(".form"),galleryEl:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn"),loaderEl:document.querySelector(".loader"),per_page:15};let h="",n=1,y=1;o.formEl.addEventListener("submit",v);o.loadMoreBtn.addEventListener("click",P);o.galleryEl.addEventListener("click",M);function M(a){a.target.nodeName==="IMG"&&a.preventDefault()}async function v(a){a.preventDefault(),b();let r=null;const e=a.target.elements["search-text"].value.trim();if(!e)return l.error({message:"Empty request. Try again!",position:"topRight"});h=e,d(),p(),n=1;try{r=await u(e,n);const i=r.hits;if(i.length===0)return l.error({message:"Sorry there are no images matching your search query. Please try again!",position:"topRight"});m(i)}catch(i){l.error({message:i.message,position:"topRight"})}finally{g(),y=Math.ceil(r.totalHits/o.per_page),r.totalHits>o.per_page&&f()}a.target.reset()}async function P(){d(),p(),n+=1;try{const r=(await u(h,n)).hits;m(r);const i=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:i*2,left:0,behavior:"smooth"})}catch(a){l.error({message:a.message,position:"topRight"})}finally{g(),n>=y?(d(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):f()}}
//# sourceMappingURL=index.js.map
